name: 'Build Debian package'
description: 'Build a Debian package'
inputs:
  sources:
    description: Any extra sources to add to apt
    required: false
    default: ''
  ppa:
    description: "An extra PPA to add to apt (no ppa: prefix)"
    required: false
    default: ''
  args:
    description: Arguments to pass to dpkg-buildpackage
    required: false
  platform:
    description: Platform to build on
    required: false
    default: linux/amd64

runs:
  using: 'composite'
  steps:
    - name: Setup QEMU
      if: ${{ !contains(inputs.platform, 'amd64') }}
      uses: docker/setup-qemu-action@v3
    - uses: ./
    - uses: actions/checkout@v4
    - name: Build Debian package
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          --platform ${{ inputs.platform }} \
          -e INPUT_SOURCES="${{ inputs.sources }}" \
          -e INPUT_PPA="${{ inputs.ppa }}" \
          -e INPUT_ARGS="${{ inputs.args }}" \
          --entrypoint /workspace/entrypoint.sh \
          ghcr.io/andy5995/gh-action-build-deb:bookworm
      shell: bash

branding:
  icon: 'package'
  color: 'gray-dark'
