name: Test Action
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: trunk
    paths:
    - 'entrypoint.sh'
    - '**Dockerfile'
    - '!**.yml'
    - '!**.md'
    - 'action.yml'
    - 'test.yml'
  pull_request:
    branches: trunk
    paths:
    - 'entrypoint.sh'
    - '**Dockerfile'
    - '!**.yml'
    - '!**.md'
    - 'action.yml'
    - 'test.yml'

jobs:
  build-deb:
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
          - 386

    runs-on: ubuntu-latest
    steps:
    - name: Checkout rmw
      uses: actions/checkout@v4
      with:
        repository: theimpossibleastronaut/rmw

    - name: Copy debian directory
      run: cp -a packaging/debian .

    - uses: ./
      with:
        args: --no-sign
        platform: ${{ matrix.platform }}

    - name: Create sha256sum
      run: |
        DEB_FILENAME=$(basename `find output/*deb`)
        echo "DEB_FILENAME=$DEB_FILENAME" >> $GITHUB_ENV
        cd output
        sha256sum "$DEB_FILENAME" > "../$DEB_FILENAME.sha256sum"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.DEB_FILENAME }}
        path: |
          output/*.deb
          *deb.sha256sum
        if-no-files-found: error
